name: Deploy to Tencent Cloud EdgeOne

on:
  # 当推送到 main 分支时触发
  push:
    branches: [ "main" ]
  # 允许手动触发工作流
  workflow_dispatch:

# 设置权限
permissions:
  contents: read
  actions: read

# 允许一个并发部署
concurrency:
  group: "edgeone"
  cancel-in-progress: false

jobs:
  # 构建作业
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          
      - name: 设置 pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
          
      - name: 获取 pnpm 存储目录
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
          
      - name: 设置 pnpm 缓存
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
          
      - name: 安装依赖
        run: pnpm install --frozen-lockfile
        
      - name: 构建网站
        run: pnpm run build
        
      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: ./dist

  # 部署到腾讯云EdgeOne
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 下载构建产物
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./dist
          
      - name: 部署到腾讯云EdgeOne
        # 这里使用腾讯云的官方部署Action，需要配置相应的secrets
        # 你需要在GitHub仓库设置中添加以下secrets：
        # TENCENT_SECRET_ID, TENCENT_SECRET_KEY, EDGEONE_ZONE_ID
        run: |
          echo "请配置腾讯云EdgeOne部署步骤"
          echo "需要在GitHub Secrets中设置："
          echo "- TENCENT_SECRET_ID"
          echo "- TENCENT_SECRET_KEY" 
          echo "- EDGEONE_ZONE_ID"
          echo "构建文件已准备在 ./dist 目录中"
          ls -la ./dist 